export const itemsCustomData = [
  {
    id: "stable-1001",
    name: "Apple MacBook Pro 16-inch",
    price: 2499.99,
    stock: 12,
    imageUrl: "",
    accountName: "Tech Store",
    categoryName: "Product",
  },
  {
    id: "stable-1002",
    name: "Samsung Galaxy S23 Ultra",
    price: 1199.99,
    stock: 20,
    imageUrl: "",
    accountName: "Mobile Hub",
    categoryName: "Product",
  },
  {
    id: "stable-1003",
    name: "Sony WH-1000XM5 Headphones",
    price: 349.99,
    stock: 15,
    imageUrl: "",
    accountName: "Gadget World",
    categoryName: "Product",
  },
  {
    id: "stable-1004",
    name: "Dell XPS 15 Laptop",
    price: 1899.99,
    stock: 10,
    imageUrl: "",
    accountName: "Tech Store",
    categoryName: "Product",
  },
  {
    id: "stable-1005",
    name: "PlayStation 5",
    price: 499.99,
    stock: 8,
    imageUrl: "",
    accountName: "Game Station",
    categoryName: "Product",
  },
  {
    id: "stable-1006",
    name: "Nike Air Max 270",
    price: 129.99,
    stock: 25,
    imageUrl: "",
    accountName: "Sports Gear",
    categoryName: "Product",
  },
  {
    id: "stable-1007",
    name: "Adidas Ultraboost",
    price: 149.99,
    stock: 18,
    imageUrl: "",
    accountName: "Sports Gear",
    categoryName: "Product",
  },
  {
    id: "stable-1008",
    name: "Professional Photography Session",
    price: 299.99,
    stock: 5,
    imageUrl: "",
    accountName: "Lens Masters",
    categoryName: "Service",
  },
  {
    id: "stable-1009",
    name: "Spa and Massage Therapy",
    price: 79.99,
    stock: 10,
    imageUrl: "",
    accountName: "Wellness Center",
    categoryName: "Service",
  },
  {
    id: "stable-1010",
    name: "Gourmet Sushi Platter",
    price: 59.99,
    stock: 30,
    imageUrl: "",
    accountName: "Tokyo Bites",
    categoryName: "Meal",
  },
  {
    id: "stable-1011",
    name: "Italian Pasta Combo",
    price: 29.99,
    stock: 25,
    imageUrl: "",
    accountName: "Pasta House",
    categoryName: "Meal",
  },
  {
    id: "stable-1012",
    name: "BBQ Ribs Special",
    price: 34.99,
    stock: 20,
    imageUrl: "",
    accountName: "Grill Masters",
    categoryName: "Meal",
  },
  {
    id: "stable-1013",
    name: "Organic Green Smoothie",
    price: 9.99,
    stock: 50,
    imageUrl: "",
    accountName: "Healthy Life",
    categoryName: "Meal",
  },
  {
    id: "stable-1014",
    name: "Business Consulting Package",
    price: 499.99,
    stock: 10,
    imageUrl: "",
    accountName: "Biz Solutions",
    categoryName: "Service",
  },
  {
    id: "stable-1015",
    name: "Home Cleaning Service",
    price: 89.99,
    stock: 15,
    imageUrl: "",
    accountName: "Clean & Fresh",
    categoryName: "Service",
  },
  {
    id: "stable-1016",
    name: "Yoga and Meditation Class",
    price: 19.99,
    stock: 20,
    imageUrl: "",
    accountName: "Zen Studio",
    categoryName: "Service",
  },
  {
    id: "stable-1017",
    name: "Classic Cheeseburger",
    price: 12.99,
    stock: 40,
    imageUrl: "",
    accountName: "Burger Joint",
    categoryName: "Meal",
  },
  {
    id: "stable-1018",
    name: "Full Car Detailing",
    price: 149.99,
    stock: 10,
    imageUrl: "",
    accountName: "Auto Care",
    categoryName: "Service",
  },
  {
    id: "stable-1019",
    name: "MacBook Air M2",
    price: 1299.99,
    stock: 10,
    imageUrl: "",
    accountName: "Tech Store",
    categoryName: "Product",
  },
  {
    id: "stable-1020",
    name: "iPad Pro 12.9-inch",
    price: 1099.99,
    stock: 15,
    imageUrl: "",
    accountName: "Tech Store",
    categoryName: "Product",
  },
  {
    id: "stable-1021",
    name: "Samsung QLED 4K TV",
    price: 799.99,
    stock: 5,
    imageUrl: "",
    accountName: "Home Electronics",
    categoryName: "Product",
  },
  {
    id: "stable-1022",
    name: "T-Bone Steak Dinner",
    price: 39.99,
    stock: 30,
    imageUrl: "",
    accountName: "Steak House",
    categoryName: "Meal",
  },
  {
    id: "stable-1023",
    name: "Digital Marketing Consultation",
    price: 299.99,
    stock: 10,
    imageUrl: "",
    accountName: "Marketing Experts",
    categoryName: "Service",
  },
  {
    id: "stable-1024",
    name: "Electric Scooter",
    price: 499.99,
    stock: 12,
    imageUrl: "",
    accountName: "E-Mobility",
    categoryName: "Product",
  },
  {
    id: "stable-1025",
    name: "Gourmet Coffee Beans",
    price: 19.99,
    stock: 40,
    imageUrl: "",
    accountName: "Coffee Lovers",
    categoryName: "Product",
  },
  {
    id: "stable-1026",
    name: "Private Coding Bootcamp",
    price: 999.99,
    stock: 5,
    imageUrl: "",
    accountName: "Code Academy",
    categoryName: "Service",
  },
  {
    id: "stable-1027",
    name: "DJ for Events",
    price: 499.99,
    stock: 7,
    imageUrl: "",
    accountName: "Party Beats",
    categoryName: "Service",
  },
  {
    id: "stable-1028",
    name: "Luxury Hotel Stay (2 Nights)",
    price: 599.99,
    stock: 10,
    imageUrl: "",
    accountName: "Elite Travel",
    categoryName: "Service",
  },
  {
    id: "stable-1029",
    name: "Smart Home Security System",
    price: 299.99,
    stock: 8,
    imageUrl: "",
    accountName: "Secure Living",
    categoryName: "Product",
  },
  {
    id: "stable-1030",
    name: "Mountain Bike",
    price: 899.99,
    stock: 6,
    imageUrl: "",
    accountName: "Adventure Gear",
    categoryName: "Product",
  },
  {
    id: "stable-1031",
    name: "Wireless Earbuds",
    price: 99.99,
    stock: 30,
    imageUrl: "",
    accountName: "Gadget World",
    categoryName: "Product",
  },
  {
    id: "stable-1032",
    name: "Gaming Mouse",
    price: 49.99,
    stock: 50,
    imageUrl: "",
    accountName: "Game Station",
    categoryName: "Product",
  },
  {
    id: "stable-1033",
    name: "Mechanical Keyboard",
    price: 89.99,
    stock: 40,
    imageUrl: "",
    accountName: "Tech Store",
    categoryName: "Product",
  },
  {
    id: "stable-1034",
    name: "4K Action Camera",
    price: 199.99,
    stock: 15,
    imageUrl: "",
    accountName: "Camera Hub",
    categoryName: "Product",
  },
  {
    id: "stable-1035",
    name: "Portable Charger",
    price: 29.99,
    stock: 60,
    imageUrl: "",
    accountName: "Mobile Hub",
    categoryName: "Product",
  },
  {
    id: "stable-1036",
    name: "Bluetooth Speaker",
    price: 59.99,
    stock: 35,
    imageUrl: "",
    accountName: "Sound Central",
    categoryName: "Product",
  },
  {
    id: "stable-1037",
    name: "Smartwatch",
    price: 199.99,
    stock: 20,
    imageUrl: "",
    accountName: "Tech Store",
    categoryName: "Product",
  },
  {
    id: "stable-1038",
    name: "Fitness Tracker",
    price: 79.99,
    stock: 25,
    imageUrl: "",
    accountName: "Sports Gear",
    categoryName: "Product",
  },
  {
    id: "stable-1039",
    name: "Electric Toothbrush",
    price: 39.99,
    stock: 30,
    imageUrl: "",
    accountName: "Health Essentials",
    categoryName: "Product",
  },
  {
    id: "stable-1040",
    name: "Hair Straightener",
    price: 49.99,
    stock: 20,
    imageUrl: "",
    accountName: "Beauty Hub",
    categoryName: "Product",
  },
  {
    id: "stable-1041",
    name: "Designer Handbag",
    price: 299.99,
    stock: 10,
    imageUrl: "",
    accountName: "Fashion House",
    categoryName: "Product",
  },
  {
    id: "stable-1042",
    name: "Luxury Sunglasses",
    price: 149.99,
    stock: 15,
    imageUrl: "",
    accountName: "Fashion House",
    categoryName: "Product",
  },
  {
    id: "stable-1043",
    name: "Perfume",
    price: 79.99,
    stock: 30,
    imageUrl: "",
    accountName: "Beauty Hub",
    categoryName: "Product",
  },
  {
    id: "stable-1044",
    name: "Makeup Kit",
    price: 59.99,
    stock: 25,
    imageUrl: "",
    accountName: "Beauty Hub",
    categoryName: "Product",
  },
  {
    id: "stable-1045",
    name: "Skincare Set",
    price: 99.99,
    stock: 20,
    imageUrl: "",
    accountName: "Beauty Hub",
    categoryName: "Product",
  },
  {
    id: "stable-1046",
    name: "Fashionable Sneakers",
    price: 89.99,
    stock: 40,
    imageUrl: "",
    accountName: "Sports Gear",
    categoryName: "Product",
  },
  {
    id: "stable-1047",
    name: "Casual T-Shirt",
    price: 19.99,
    stock: 50,
    imageUrl: "",
    accountName: "Fashion House",
    categoryName: "Product",
  },
  {
    id: "stable-1048",
    name: "Denim Jeans",
    price: 39.99,
    stock: 40,
    imageUrl: "",
    accountName: "Fashion House",
    categoryName: "Product",
  },
  {
    id: "stable-1049",
    name: "Summer Dress",
    price: 49.99,
    stock: 30,
    imageUrl: "",
    accountName: "Fashion House",
    categoryName: "Product",
  },
  {
    id: "stable-1050",
    name: "Leather Jacket",
    price: 199.99,
    stock: 10,
    imageUrl: "",
    accountName: "Fashion House",
    categoryName: "Product",
  },
  {
    id: "stable-1051",
    name: "Grilled Chicken Salad",
    price: 12.99,
    stock: 35,
    imageUrl: "",
    accountName: "Burger Joint",
    categoryName: "Meal",
  },
  {
    id: "stable-1052",
    name: "Vegan Burger",
    price: 10.99,
    stock: 40,
    imageUrl: "",
    accountName: "Green Eats",
    categoryName: "Meal",
  },
  {
    id: "stable-1053",
    name: "Poke Bowl",
    price: 14.99,
    stock: 30,
    imageUrl: "",
    accountName: "Tokyo Bites",
    categoryName: "Meal",
  },
  {
    id: "stable-1054",
    name: "Spicy Ramen",
    price: 11.99,
    stock: 25,
    imageUrl: "",
    accountName: "Ramen House",
    categoryName: "Meal",
  },
  {
    id: "stable-1055",
    name: "BBQ Chicken Pizza",
    price: 16.99,
    stock: 20,
    imageUrl: "",
    accountName: "Pizza Place",
    categoryName: "Meal",
  },
  {
    id: "stable-1056",
    name: "Caesar Salad",
    price: 8.99,
    stock: 30,
    imageUrl: "",
    accountName: "Burger Joint",
    categoryName: "Meal",
  },
  {
    id: "stable-1057",
    name: "Falafel Wrap",
    price: 7.99,
    stock: 40,
    imageUrl: "",
    accountName: "Green Eats",
    categoryName: "Meal",
  },
  {
    id: "stable-1058",
    name: "Fish and Chips",
    price: 13.99,
    stock: 25,
    imageUrl: "",
    accountName: "Seafood Shack",
    categoryName: "Meal",
  },
  {
    id: "stable-1059",
    name: "Steak Sandwich",
    price: 15.99,
    stock: 20,
    imageUrl: "",
    accountName: "Steak House",
    categoryName: "Meal",
  },
  {
    id: "stable-1060",
    name: "Chocolate Cake",
    price: 6.99,
    stock: 50,
    imageUrl: "",
    accountName: "Sweet Treats",
    categoryName: "Meal",
  },
  {
    id: "stable-1061",
    name: "Ice Cream Sundae",
    price: 4.99,
    stock: 60,
    imageUrl: "",
    accountName: "Sweet Treats",
    categoryName: "Meal",
  },
  {
    id: "stable-1062",
    name: "Fruit Smoothie Bowl",
    price: 7.99,
    stock: 40,
    imageUrl: "",
    accountName: "Healthy Life",
    categoryName: "Meal",
  },
  {
    id: "stable-1063",
    name: "Spaghetti Bolognese",
    price: 12.99,
    stock: 30,
    imageUrl: "",
    accountName: "Pasta House",
    categoryName: "Meal",
  },
  {
    id: "stable-1064",
    name: "Sushi Roll Combo",
    price: 16.99,
    stock: 35,
    imageUrl: "",
    accountName: "Tokyo Bites",
    categoryName: "Meal",
  },
  {
    id: "stable-1065",
    name: "Taco Platter",
    price: 14.99,
    stock: 30,
    imageUrl: "",
    accountName: "Mexican Fiesta",
    categoryName: "Meal",
  },
  {
    id: "stable-1066",
    name: "Vegan Salad Bowl",
    price: 9.99,
    stock: 40,
    imageUrl: "",
    accountName: "Green Eats",
    categoryName: "Meal",
  },
  {
    id: "stable-1067",
    name: "Mediterranean Platter",
    price: 13.99,
    stock: 30,
    imageUrl: "",
    accountName: "Mediterraneo",
    categoryName: "Meal",
  },
  {
    id: "stable-1068",
    name: "Dim Sum Assortment",
    price: 17.99,
    stock: 20,
    imageUrl: "",
    accountName: "Asian Delights",
    categoryName: "Meal",
  },
  {
    id: "stable-1069",
    name: "Pad Thai",
    price: 11.99,
    stock: 35,
    imageUrl: "",
    accountName: "Thai Taste",
    categoryName: "Meal",
  },
  {
    id: "stable-1070",
    name: "Curry Rice Bowl",
    price: 10.99,
    stock: 30,
    imageUrl: "",
    accountName: "Spice Hub",
    categoryName: "Meal",
  },
  {
    id: "stable-1071",
    name: "Consulting Session (30 min)",
    price: 49.99,
    stock: 15,
    imageUrl: "",
    accountName: "Biz Solutions",
    categoryName: "Service",
  },
  {
    id: "stable-1072",
    name: "Web Design Package",
    price: 399.99,
    stock: 10,
    imageUrl: "",
    accountName: "Creative Studio",
    categoryName: "Service",
  },
  {
    id: "stable-1073",
    name: "SEO Optimization Service",
    price: 299.99,
    stock: 12,
    imageUrl: "",
    accountName: "Marketing Experts",
    categoryName: "Service",
  },
  {
    id: "stable-1074",
    name: "Social Media Management",
    price: 199.99,
    stock: 8,
    imageUrl: "",
    accountName: "Marketing Experts",
    categoryName: "Service",
  },
  {
    id: "stable-1075",
    name: "App Development Service",
    price: 999.99,
    stock: 5,
    imageUrl: "",
    accountName: "Tech Solutions",
    categoryName: "Service",
  },
  {
    id: "stable-1076",
    name: "Logo Design",
    price: 149.99,
    stock: 20,
    imageUrl: "",
    accountName: "Creative Studio",
    categoryName: "Service",
  },
  {
    id: "stable-1077",
    name: "Copywriting Service",
    price: 99.99,
    stock: 25,
    imageUrl: "",
    accountName: "Content Pros",
    categoryName: "Service",
  },
  {
    id: "stable-1078",
    name: "Virtual Assistant Package",
    price: 79.99,
    stock: 30,
    imageUrl: "",
    accountName: "Biz Solutions",
    categoryName: "Service",
  },
  {
    id: "stable-1079",
    name: "Legal Consultation",
    price: 149.99,
    stock: 10,
    imageUrl: "",
    accountName: "Legal Advisors",
    categoryName: "Service",
  },
  {
    id: "stable-1080",
    name: "Financial Planning",
    price: 199.99,
    stock: 8,
    imageUrl: "",
    accountName: "Finance Experts",
    categoryName: "Service",
  },
  {
    id: "stable-1081",
    name: "Interior Design Consultation",
    price: 299.99,
    stock: 5,
    imageUrl: "",
    accountName: "Design Studio",
    categoryName: "Service",
  },
  {
    id: "stable-1082",
    name: "Event Planning",
    price: 399.99,
    stock: 6,
    imageUrl: "",
    accountName: "Event Pros",
    categoryName: "Service",
  },
  {
    id: "stable-1083",
    name: "Photography Workshop",
    price: 89.99,
    stock: 15,
    imageUrl: "",
    accountName: "Lens Masters",
    categoryName: "Service",
  },
  {
    id: "stable-1084",
    name: "Cooking Class",
    price: 59.99,
    stock: 20,
    imageUrl: "",
    accountName: "Culinary Academy",
    categoryName: "Service",
  },
  {
    id: "stable-1085",
    name: "Language Tutoring",
    price: 39.99,
    stock: 25,
    imageUrl: "",
    accountName: "Tutor Hub",
    categoryName: "Service",
  },
  {
    id: "stable-1086",
    name: "Music Lessons",
    price: 49.99,
    stock: 15,
    imageUrl: "",
    accountName: "Music Academy",
    categoryName: "Service",
  },
  {
    id: "stable-1087",
    name: "Fitness Training",
    price: 29.99,
    stock: 30,
    imageUrl: "",
    accountName: "Gym Pro",
    categoryName: "Service",
  },
  {
    id: "stable-1088",
    name: "Haircut & Styling",
    price: 19.99,
    stock: 20,
    imageUrl: "",
    accountName: "Beauty Salon",
    categoryName: "Service",
  },
  {
    id: "stable-1089",
    name: "Nail Art Session",
    price: 14.99,
    stock: 25,
    imageUrl: "",
    accountName: "Beauty Salon",
    categoryName: "Service",
  },
  {
    id: "stable-1090",
    name: "Spa Treatment Package",
    price: 99.99,
    stock: 10,
    imageUrl: "",
    accountName: "Wellness Center",
    categoryName: "Service",
  },
  {
    id: "stable-1091",
    name: "Car Wash Service",
    price: 24.99,
    stock: 40,
    imageUrl: "",
    accountName: "Auto Care",
    categoryName: "Service",
  },
  {
    id: "stable-1092",
    name: "Lawn Mowing",
    price: 29.99,
    stock: 20,
    imageUrl: "",
    accountName: "Garden Pros",
    categoryName: "Service",
  },
  {
    id: "stable-1093",
    name: "House Painting",
    price: 399.99,
    stock: 3,
    imageUrl: "",
    accountName: "RenovateIt",
    categoryName: "Service",
  },
  {
    id: "stable-1094",
    name: "Plumbing Service",
    price: 89.99,
    stock: 10,
    imageUrl: "",
    accountName: "FixIt Plumbing",
    categoryName: "Service",
  },
  {
    id: "stable-1095",
    name: "Electrical Repairs",
    price: 99.99,
    stock: 10,
    imageUrl: "",
    accountName: "Spark Electric",
    categoryName: "Service",
  },
  {
    id: "stable-1096",
    name: "Grocery Delivery",
    price: 19.99,
    stock: 50,
    imageUrl: "",
    accountName: "Quick Grocers",
    categoryName: "Service",
  },
  {
    id: "stable-1097",
    name: "Pet Grooming",
    price: 34.99,
    stock: 15,
    imageUrl: "",
    accountName: "Pet Care",
    categoryName: "Service",
  },
  {
    id: "stable-1098",
    name: "Dog Walking",
    price: 14.99,
    stock: 25,
    imageUrl: "",
    accountName: "Pet Care",
    categoryName: "Service",
  },
  {
    id: "stable-1099",
    name: "Virtual Fitness Class",
    price: 9.99,
    stock: 50,
    imageUrl: "",
    accountName: "Gym Pro",
    categoryName: "Service",
  },
  {
    id: "stable-1100",
    name: "Online Cooking Tutorial",
    price: 39.99,
    stock: 50,
    imageUrl: "",
    accountName: "Culinary Academy",
    categoryName: "Service",
  },
];
